name: CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        
    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-22.04  

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Get commit SHA as version
      run: >
        echo "{version}={${{ github.sha }}}" >> GITHUB_ENV 
        echo "Sha: ${{ env.version }}"

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      
    - name: Restore NuGet Packages
      run: dotnet restore
      
    - name: Restore NuGet Workload
      run: dotnet workload restore
    
    - name: Build for linux
      run: >
        dotnet publish ./EK.Discord.Server/EK.Discord.Server.csproj
        --configuration Release 
        --output ./Build/Linux/ 
        --self-contained 
        --runtime linux-x64
        
    - name: Build the Docker image
      run: >
        docker build 
        --file ./.github/workflows/Dockerfile 
        --tag maglethong/ek/discord/jester:${{ env.version }}
        .

    - name: Export docker image
      run: >
        docker image save 
        --output ./DockerImage
        --tag maglethong/ek/discord/jester:${{steps.vars.outputs.sha}} 
        .
    
    - name: Archive built Docker image
      uses: actions/upload-artifact@v3
      with:
        name: DockerImage
        path: ./DockerImage
    
    - name: AZURE LOGIN
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
      
    - name: Deploy
      run: echo TODO
  
  
  
